### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by gllmhyt** [mommel/letsencrypt-aplus#2]
It would be great to also support the Nginx configuration.

**Comment by mommel** [comment]
:+1: Yes why not

**Comment by mommel** [comment]
Didn't test it by now but maybe that works for you https://github.com/mommel/letsencrypt-aplus/tree/features/nginx-support

**Comment by gllmhyt** [comment]
I'll test it.

**Comment by mommel** [comment]
Now it should result in a+, merged in master.
Thanks
